using Microsoft.CodeAnalysis;

namespace Analyser.ForceSetProperties.Emission
{
    /// <summary>
    /// Emits the [ForceSetProperties] attribute as source into every consuming compilation,
    /// so consumers only need an &lt;Analyzer&gt; reference and never a normal project/package
    /// reference to this analyzer's assembly.
    /// </summary>
    public static class AttributeEmitter
    {
        public const string AttributeClassName = "ForceSetPropertiesAttribute";
        public const string TypesPropertyName = "Types";
        public const string AttributeHintName = AttributeClassName + ".g.cs";

        public static void Emit(IncrementalGeneratorPostInitializationContext context)
            => context.AddSource(AttributeHintName, Source);

        // Exposed so tests can compile source snippets against the same attribute definition
        // that gets injected into real consumers, rather than maintaining a duplicate.
        public static readonly string Source = """
            // <auto-generated/>

            using System;

            namespace Analyser.ForceSetProperties
            {
                /// <summary>
                /// Forces every settable property of the target type to be assigned wherever this
                /// attribute is applied, failing compilation if one is missed. Apply to a constructor,
                /// method, or expression-bodied property/lambda that creates the type (not yet supported
                /// on a class). The target type is inferred from the return type unless overridden via
                /// <see cref="Types"/> or the generic <c>ForceSetProperties&lt;T&gt;</c> form.
                /// </summary>
                public class ForceSetPropertiesAttribute : Attribute
                {
                    /// <summary>Infers the target type from the return type of the annotated member.</summary>
                    public ForceSetPropertiesAttribute() { }

                    /// <summary>Explicitly specifies one or more target types to validate.</summary>
                    public ForceSetPropertiesAttribute(params Type[] types)
                    {
                        Types = types;
                    }

                    /// <summary>The explicit target type(s) to validate, overriding return-type inference.</summary>
                    public Type[] Types { get; set; } = Array.Empty<Type>();
                }

                /// <summary>
                /// Shorthand for <see cref="ForceSetPropertiesAttribute"/> with the target type fixed to
                /// <typeparamref name="T"/>, for use when it differs from (or can't be inferred from) the
                /// annotated member's return type.
                /// </summary>
                public class ForceSetPropertiesAttribute<T> : ForceSetPropertiesAttribute
                {
                    /// <summary>Sets the target type to <typeparamref name="T"/>.</summary>
                    public ForceSetPropertiesAttribute()
                    {
                        Types = new[] { typeof(T) };
                    }
                }
            }
            """;
    }
}
